### ISSUE TITLE
train val test file

### ISSUE THREAD

**Issue by PriscaCommit** [GeoZcx/A-deeply-supervised-image-fusion-network-for-change-detection-in-remote-sensing-images#23]
是否能够分享您的训练，验证，测试的源码，万分感谢

**Comment by rlcgetUp** [comment]
yes,can you share your train,validation and test code?

**Comment by songyvying** [comment]
@yuanpanlifly   Hello, may I ask if you have got the complete code? Because I have been reading this paper recently and want to reproduce it, but because I just got into this direction and am not competent enough, I want to get the complete code to learn, thank you!  1941167521@qq.com

**Comment by rlcgetUp** [comment]
I don't have complete code and I still don't reproduce it .The autor just provide the pytorch and tensorflow version's code. I also only have it.




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年4月29日(星期五) 晚上9:41
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [GeoZcx/A-deeply-supervised-image-fusion-network-for-change-detection-in-remote-sensing-images] train val test file (Issue #23)





 
@yuanpanlifly   Hello, may I ask if you have got the complete code? Because I have been reading this paper recently and want to reproduce it, but because I just got into this direction and am not competent enough, I want to get the complete code to learn, thank you!  ***@***.***
